version: "3.9"

services:
  api:
    build: .
    container_name: chatbot-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatbotapi
      - DATABASE_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_HOSTNAME=db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge
