API_PORT=80
HOST=0.0.0.0


.PHONY: run-app
run-app:
	uvicorn chatbot_api.main:app --host $(HOST) --port $(API_PORT)


.PHONY: run-app-dev
run-app-dev:
	uvicorn chatbot_api.main:app --host $(HOST) --port $(API_PORT) --reload
